/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TPOS;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;
import java.sql.Statement;
import javax.swing.Timer;

/**
 *
 * @author Chethiya
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public POS() {
        initComponents();
        date();
        startDateTimeTimer();
    }
    
    
    String lname,date,time;
    
    public POS(String name) {
        initComponents();
        this.lname = name;
        jLableUname.setText(lname);
        date();
        startDateTimeTimer();
    }


    public void date(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DateTimeFormatter tdf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        date = dtf.format(now);
        time = tdf.format(now);

        jLableDate.setText(date);
        jLableTime.setText(time);
        
    }
   
    private void startDateTimeTimer() {
        Timer timer = new Timer(1000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date();
            }
        });
        timer.start();
    }
    
    
    PreparedStatement insert,stm;
    Connection conn;
    ResultSet rs;
    DefaultTableModel tb1 = new DefaultTableModel();
    
    Timer errorMessageTimer;
    private final int ERROR_MESSAGE_DURATION = 5000; 
    
    private void errorMessage(){
        errorMessageTimer = new Timer(ERROR_MESSAGE_DURATION, e->{
            jLabelError.setText("");
            jLabelSuccess.setText("");
            errorMessageTimer.stop();
        });
        errorMessageTimer.setRepeats(false);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFProduct_Code = new javax.swing.JTextField();
        jButton_Add = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTFPrice = new javax.swing.JTextField();
        jTFQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFProduct_Name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButon_Delete = new javax.swing.JButton();
        jButon_Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTFSubT = new javax.swing.JTextField();
        jTFPay = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTFBalance = new javax.swing.JTextField();
        jButon_PayInvoice = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLableUname = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLableDate = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLableTime = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jLabelSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/cashier_small.png"))); // NOI18N
        jButton1.setText("Cashier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/category_small.png"))); // NOI18N
        jButton2.setText("Category");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/brand_small.png"))); // NOI18N
        jButton3.setText("Brand");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/product_small.png"))); // NOI18N
        jButton4.setText("Product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/logout.png"))); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogout)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jButtonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("POS");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Product Code :");

        jTFProduct_Code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTFProduct_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFProduct_CodeKeyPressed(evt);
            }
        });

        jButton_Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/add.png"))); // NOI18N
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Price :");

        jTFPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTFQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Product Name :");

        jTFProduct_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Qty :");

        jButon_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButon_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/cancel.png"))); // NOI18N
        jButon_Delete.setText("Delete");
        jButon_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon_DeleteActionPerformed(evt);
            }
        });

        jButon_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButon_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/edit.png"))); // NOI18N
        jButon_Update.setText("Update");
        jButon_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTFPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFProduct_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(83, 83, 83))
                    .addComponent(jTFProduct_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTFQty, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButon_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButon_Update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_Add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButon_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButon_Delete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFProduct_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFProduct_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFQty, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Sub Total :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Pay :");

        jTFSubT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTFPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Balance :");

        jTFBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButon_PayInvoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButon_PayInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/pay.png"))); // NOI18N
        jButon_PayInvoice.setText("Pay invoice");
        jButon_PayInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon_PayInvoiceActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 255));

        jLableUname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLableUname.setForeground(new java.awt.Color(51, 51, 51));
        jLableUname.setText("#");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("User:");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/TPOS Logo.png"))); // NOI18N

        jLableDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLableDate.setForeground(new java.awt.Color(51, 51, 51));
        jLableDate.setText("#");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Date :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Time :");

        jLableTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLableTime.setForeground(new java.awt.Color(51, 51, 51));
        jLableTime.setText("#");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPOS/icons/cancel.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 51, 51));

        jLabelSuccess.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelSuccess.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTFSubT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTFPay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(376, 376, 376))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButon_PayInvoice)
                                        .addGap(16, 16, 16))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(311, 311, 311)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLableDate)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLableTime)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLableUname)
                                .addGap(128, 128, 128))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLableUname)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLableDate)
                    .addComponent(jLabel21)
                    .addComponent(jLableTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(jTFPay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(9, 9, 9)
                            .addComponent(jTFSubT))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButon_PayInvoice)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pos(){
        errorMessage();
        tb1 = (DefaultTableModel)jTable1.getModel();
           
        String pcode = jTFProduct_Code.getText();
        String pName = jTFProduct_Name.getText();
        String strPrice = jTFPrice.getText();
        String qty = jTFQty.getText();
        
        if (pcode.isEmpty()) {
            jLabelError.setText("Enter product code and then press Enter!");
            errorMessageTimer.start();
            return;
        }
        
        if (pName.isEmpty()) {
            jLabelError.setText("Enter product name!");
            errorMessageTimer.start();
            return;
        }
        
        if (strPrice.isEmpty()) {
            jLabelError.setText("Enter product price!");
            errorMessageTimer.start();
            return;
        }
        
        if (qty.isEmpty()) {
            jLabelError.setText("Enter product qty!");
            errorMessageTimer.start();
            return;
        }
        
        boolean productExists = false;
        for (int i = 0; i < tb1.getRowCount(); i++) {
            String existingCode = tb1.getValueAt(i, 0).toString();
            if (existingCode.equals(pcode)) {
                productExists = true;
                break;
            }
        }
        
        if (productExists) {
            jLabelError.setText("Product already added to the table!");
            errorMessageTimer.start();
            return;
        }
            
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPOS", "root", "");
                insert = conn.prepareStatement("Select * from Product where Barcode = ?");
                insert.setString(1, pcode);
                rs = insert.executeQuery(); 

            while (rs.next()) {       
                
                int current_qty;
                current_qty = rs.getInt("Qty");

                if(current_qty == 0){  
                    jLabelError.setText("This product stock is empty!!! Restock NOW!!!");
                    return;

                }else if(current_qty < 10){
                    jLabelError.setText(current_qty +" items available!!! Please restock!!!");
                    errorMessageTimer.start();
                    
                    int price = Integer.parseInt(jTFPrice.getText());
                    int new_qty = Integer.parseInt(jTFQty.getText());

                    int tot = price * new_qty;

                    if(new_qty > current_qty ){
//                        JOptionPane.showMessageDialog(this, "Quantity is not enough!!!  " + current_qty + "  Available in stock");
                        jLabelError.setText("Quantity is not enough!!!  " + current_qty + "  Available in stock");
                        errorMessageTimer.start();
                        return;

                    }
                    else{
                        
                        if (new_qty == current_qty) {
                            jLabelError.setText("0 Available in stock! RESTOCK NOW!!!");
                        }
                        
                        tb1 = (DefaultTableModel)jTable1.getModel();
                        tb1.addRow(new Object[]{
                            jTFProduct_Code.getText(),
                            jTFProduct_Name.getText(),
                            jTFPrice.getText(),
                            jTFQty.getText(),
                            tot,
                        });

                        int sum = 0;

                        for(int i = 0; i < jTable1.getRowCount(); i++){
                            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                        }

                        jTFSubT.setText(Integer.toString(sum));
                        jTFProduct_Code.setText("");
                        jTFProduct_Name.setText("");
                        jTFPrice.setText("");
                        jTFQty.setText("");

                    }
                
                }else{
                    jLabelError.setText("");
                    
                    int price = Integer.parseInt(jTFPrice.getText());
                    int new_qty = Integer.parseInt(jTFQty.getText());

                    int tot = price * new_qty;
                    

                    if(new_qty >= current_qty ){
//                        JOptionPane.showMessageDialog(this, "Quantity is not enough!!!  " + current_qty + "  Available in stock");
//                        JOptionPane.showMessageDialog(this, "Quantity is not enough!!!");
                        jLabelError.setText("Only " + current_qty +" available in stock!");
                        errorMessageTimer.start();
                        return;

                    }else{
                        tb1 = (DefaultTableModel)jTable1.getModel();
                        tb1.addRow(new Object[]{
                            jTFProduct_Code.getText(),
                            jTFProduct_Name.getText(),
                            jTFPrice.getText(),
                            jTFQty.getText(),
                            tot,
                        });

                        int sum = 0;

                        for(int i = 0; i < jTable1.getRowCount(); i++){
                            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                        }

                        jTFSubT.setText(Integer.toString(sum));
                        jTFProduct_Code.setText("");
                        jTFProduct_Name.setText("");
                        jTFPrice.setText("");
                        jTFQty.setText("");

                           // jTFPay

                    }
                
                }
            }

 
            } catch (SQLException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            }

    
    }

    
    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
       
         pos(); 
            
         
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();
        if (selectIndex >= 0) {
            jTFProduct_Name.setText(d.getValueAt(selectIndex, 1).toString());
            jTFPrice.setText(d.getValueAt(selectIndex, 2).toString());
            jTFQty.setText(d.getValueAt(selectIndex, 3).toString());
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTFProduct_CodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProduct_CodeKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        
            String code = jTFProduct_Code.getText();
            
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPOS", "root", "");
                insert = conn.prepareStatement("Select * from Product where Barcode = ?");
                insert.setString(1, code);
                rs = insert.executeQuery();
                
                if(rs.next() == false){
                    jLabelError.setText("Product code not found!!!");
//                    JOptionPane.showMessageDialog(this, "Barcode not found!!!");
                    
                    
                }else{
                
                    String pname = rs.getString("Product_Name");
                    String price = rs.getString("Retail_Price");
                    
                    jTFProduct_Name.setText(pname.trim());
                    jTFPrice.setText(price.trim());
                    
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        
        } 
        
    }//GEN-LAST:event_jTFProduct_CodeKeyPressed

    private void jButon_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon_DeleteActionPerformed
     
        errorMessage();
    
    if (jTable1.getRowCount() == 0) {
        jLabelError.setText("No items to delete!");
        errorMessageTimer.start();
        return;
    }
    
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        jLabelError.setText("Please select item to Delete!");
        errorMessageTimer.start();
        return;
    }
    
    // Get id (barcode) before potential deletion
    tb1 = (DefaultTableModel) jTable1.getModel(); // Ensure tb1 is set
    String idStr = tb1.getValueAt(selectedRow, 0).toString(); // Get barcode
    int id;
    try {
        id = Integer.parseInt(idStr); // Try to parse, assuming barcode is numeric
    } catch (NumberFormatException e) {
        jLabelError.setText("Invalid barcode format for deletion!");
        errorMessageTimer.start();
        return;
    }
    
    // Show confirmation dialog first
    int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete product item from table?","Warning",JOptionPane.YES_NO_OPTION);
    
    if(dialogResult == JOptionPane.YES_OPTION){
        // Remove row from table
        tb1.removeRow(selectedRow);
        
        // Recalculate subtotal
        int del = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++){
            del += Integer.parseInt(jTable1.getValueAt(i, 4).toString());
        }
        jTFSubT.setText(Integer.toString(del));
        
        // Database deletion (assuming this is needed, though per previous, should be deferred)
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPOS", "root", "");
            String sql = "Delete from Sales WHERE id = ?";
            stm = conn.prepareStatement(sql);
            stm.setInt(1, id);
            stm.executeUpdate();

            jLabelSuccess.setText("Product Deleted!");
            errorMessageTimer.start();

            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
            jLabelError.setText("Database error during deletion: " + ex.getMessage());
            errorMessageTimer.start();
        }
    } else {
        jLabelError.setText("Deletion cancelled.");
        errorMessageTimer.start();
    }
        
    }//GEN-LAST:event_jButon_DeleteActionPerformed

    private void sales(){
    
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        String cashier = jLableUname.getText();
        String subtot = jTFSubT.getText();
        String pay = jTFPay.getText();
        String balance = jTFBalance.getText();
        int lastinsertid = 0;
        
        
        if (cashier.isEmpty() || subtot.isEmpty() || pay.isEmpty()  || balance.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "All fields are required!");
            jLabelError.setText("All fields are required!");
            errorMessageTimer.start();
            return;
        }
        
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPOS", "root", "");  //connects with the database
            String sql = "INSERT INTO Sales( Date,Cashier, Sub_Total, Pay, Balance) VALUES (?, ?, ?, ?,?)"; //inserts data into database
            insert = conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS); //prepares a statement to run the query instead of compiling first 
            insert.setString(1, date); //set values
            insert.setString(2, cashier);
            insert.setString(3, subtot); //set values
            insert.setString(4, pay);
            insert.setString(5, balance);
            insert.executeUpdate(); // runs the sql statement
            //JOptionPane.showMessageDialog(null,"Sale added!");
            ResultSet genkeyres = insert.getGeneratedKeys();
            
            if(genkeyres.next()){
            
                lastinsertid = genkeyres.getInt(1);
            
            }else{
            
                JOptionPane.showMessageDialog(this, lastinsertid);
                
            }
            
            int rows = jTable1.getRowCount();
            
            String sql2 = "INSERT INTO sales_product(Sales_ID, Product_ID, Sell_Price, Qty, Total) VALUES (?, ?, ?, ?, ?)";
            insert = conn.prepareStatement(sql2);
            
            String product_id = "";
            String price = "";
            String qty = "";
            int total = 0;
            
            
            for(int i = 0; i<jTable1.getRowCount(); i++){
            
                product_id = (String)jTable1.getValueAt(i, 0);
                price = (String)jTable1.getValueAt(i, 2);
                qty = (String)jTable1.getValueAt(i, 3);
                total = (int)jTable1.getValueAt(i, 4);
                
                insert.setInt(1, lastinsertid);
                insert.setString(2, product_id);
                insert.setString(3, price);
                insert.setString(4, qty);
                insert.setInt(5, total);
                insert.executeUpdate();
                
            }
            
            String sql3 = "Update product set Qty = Qty-? where Barcode = ?";
            insert = conn.prepareStatement(sql3);
            
            for(int i = 0; i<jTable1.getRowCount(); i++){
            
                product_id = (String)jTable1.getValueAt(i, 0);
                qty = (String)jTable1.getValueAt(i, 3);
                
                insert.setString(1, qty);
                insert.setString(2, product_id);
                insert.executeUpdate();
                
            }
            
            insert.addBatch();
//            JOptionPane.showMessageDialog(this, "Record Saved!!");
            jLabelSuccess.setText("Record Saved!!");
            
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    public void print(){
    
        String sub = jTFSubT.getText();
        String pay = jTFPay.getText();
        String bal = jTFBalance.getText();
        String bqty = jTFQty.getText();
        
        try {
            new Print(sub,pay,bal,bqty,jTable1.getModel()).setVisible(true);
        } catch (PrinterException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    
    
    private void jButon_PayInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon_PayInvoiceActionPerformed
        
        int pay = Integer.parseInt(jTFPay.getText());
        int sub = Integer.parseInt(jTFSubT.getText());

        int bal = pay - sub;
        
        if (pay < sub) {
            jLabelError.setText("Payment amount should be larger than Subtotal!");
            errorMessageTimer.start();
            return;
        }
        
        jTFBalance.setText(String.valueOf(bal));
        print();
        sales();
        
        
    }//GEN-LAST:event_jButon_PayInvoiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cashier ca = new Cashier();
        this.hide();
        ca.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Category c = new Category();
        this.hide();
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Brand b = new Brand();
        this.hide();
        b.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Product p = new Product();
        this.hide();
        p.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButon_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon_UpdateActionPerformed
        errorMessage();
        if (jTable1.getRowCount() == 0) {
            jLabelError.setText("Table is empty, nothing to update!");
            errorMessageTimer.start();
            return;
        }

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            jLabelError.setText("Please select a row to update!");
            errorMessageTimer.start();
            return;
        }

        String newQtyStr = jTFQty.getText().trim();
        if (newQtyStr.isEmpty()) {
            jLabelError.setText("Please enter a new quantity!");
            errorMessageTimer.start();
            return;
        }
        
        try {
            int newQty = Integer.parseInt(newQtyStr);
            
            if (newQty <= 0) {
                jLabelError.setText("Quantity must be greater than 0!");
                errorMessageTimer.start();
                return;
            }

            String barcode = tb1.getValueAt(selectedRow, 0).toString();
            int price = Integer.parseInt(tb1.getValueAt(selectedRow, 2).toString());

            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/TPOS", "root", "");
                stm = conn.prepareStatement("SELECT Qty FROM Product WHERE Barcode = ?");
                stm.setString(1, barcode);
                rs = stm.executeQuery();
                
                

                if (rs.next()) {
                    int currentStock = rs.getInt("Qty");
                    int originalQty = Integer.parseInt(tb1.getValueAt(selectedRow, 3).toString());
                    int stockAdjustment = originalQty - newQty;
                    int newStock = currentStock + stockAdjustment;
                    int maxAllow = currentStock;
                    
                    if (newQty > maxAllow) {
                        jLabelError.setText("Insufficient stock! Max allowed: " + maxAllow);
                        errorMessageTimer.start();
                        return;
                    }

                    if (newStock < 0) {
                        int maxAllowed = currentStock + originalQty;
                        jLabelError.setText("Insufficient stock! Max allowed: " + maxAllowed);
                        errorMessageTimer.start();
                    } else {
                        int newTotal = price * newQty;
                        tb1.setValueAt(newQty, selectedRow, 3);
                        tb1.setValueAt(newTotal, selectedRow, 4);

                        int sum = 0;
                        for (int i = 0; i < jTable1.getRowCount(); i++) {
                            sum += Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                        }
                        if (sum <= 0) {
                            jLabelError.setText("Subtotal must be greater than zero!");
                            errorMessageTimer.start();
                            tb1.setValueAt(originalQty, selectedRow, 3);
                            tb1.setValueAt(originalQty * price, selectedRow, 4);
                        } else {
                            jTFSubT.setText(Integer.toString(sum));
                            jTFProduct_Name.setText("");
                            jTFPrice.setText("");
                            jTFQty.setText("");
                            jLabelSuccess.setText("Item updated in sale!");
//                            errorMessageTimer.start();
//                            JOptionPane.showMessageDialog(null, "Item updated successfully!");

                        }
                    }
                } else {
                    jLabelError.setText("Product not found!");
                    errorMessageTimer.start();
                }

                rs.close();
                stm.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
                jLabelError.setText("Database error: " + ex.getMessage());
                errorMessageTimer.start();
            }
        } catch (NumberFormatException ex) {
            jLabelError.setText("️Invalid quantity format!");
            errorMessageTimer.start();
        }
        
    }//GEN-LAST:event_jButon_UpdateActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButon_Delete;
    private javax.swing.JButton jButon_PayInvoice;
    private javax.swing.JButton jButon_Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelSuccess;
    private javax.swing.JLabel jLableDate;
    private javax.swing.JLabel jLableTime;
    private javax.swing.JLabel jLableUname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBalance;
    private javax.swing.JTextField jTFPay;
    private javax.swing.JTextField jTFPrice;
    private javax.swing.JTextField jTFProduct_Code;
    private javax.swing.JTextField jTFProduct_Name;
    private javax.swing.JTextField jTFQty;
    private javax.swing.JTextField jTFSubT;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
